### ISSUE TITLE
Not working in gmail.

### ISSUE THREAD

**Issue by DracoClaw** [jkingsman/Replace-As-You-Type#1]
I need to use this in Gmail to sign emails and share my website. But it won't work.

**Comment by jkingsman** [comment]
Thanks for the report! I've fixed this with the most recent revision, which is up in the Chrome store. It also seems that at some point I accidentally broke the ability to backspace and cancel the replacement, which now works properly.

Have a great day 🙂

**Comment by DracoClaw** [comment]
It still doesn't seem to be working. Is there something I have to do?

**Comment by jkingsman** [comment]
Most likely your browser just hasn't gotten the update yet. Try giving this a shot: https://timleland.com/how-to-manually-update-google-chrome-extensions/

Your extensions page should show the extension version at 0.0.4, which is the latest one I pushed earlier.

Also, due to inherent limitations, the replace will only work when it's the last thing in the field you're typing in -- that is, if you have text below where you're trying to do the replacement, it won't work. I'm poking at solving this limitation now but no promises.

**Comment by DracoClaw** [comment]
I was on 0.0.4 I guess the issue was that I have a signature at the bottom

**Comment by jkingsman** [comment]
Yeah that will do it, unfortunately 🙁 sorry about that limitation!
